/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author helal
 */
public class DBConnect extends javax.swing.JFrame {

    DatabaseConector db = new DatabaseConector();
    boolean softSave = false;
    Validation val = new Validation();

    /**
     * Creates new form DBConnect
     */
    public DBConnect() {
        initComponents();
        setTitle("Database Connection");
        softSave = false;
        dbConnectTitle.setText("Softwere Database Connection");
        dbCreatePannel.setVisible(true);
        databaseTabPane.setEnabledAt(1, true);
        setTitle("Database Connection");
    }
//     public DBConnect(String title) {
//        initComponents();
//        dbConnectTitle.setText(title);
//        dbCreatePannel.setVisible(false);
//        setTitle("Software Database Connection");
//    }

    DBConnect(String sofware_Server_Connect) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        dbConnectTitle.setText(sofware_Server_Connect);
        dbCreatePannel.setVisible(false);
        databaseTabPane.setEnabledAt(1, false);
        setTitle("Software Database Connection");
        softSave = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databaseTabPane = new javax.swing.JTabbedPane();
        dbConnectPanel = new javax.swing.JPanel();
        dbConnectTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        driver = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        test_btn = new javax.swing.JButton();
        checkDB = new javax.swing.JCheckBox();
        dbCreatePannel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        driver_c = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        url_c = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        user_c = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        password_c = new javax.swing.JTextField();
        create_btn = new javax.swing.JButton();
        test_con_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dbName = new javax.swing.JTextField();
        check_create = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dbConnectTitle.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        dbConnectTitle.setText("Database Connect ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Driver:");

        driver.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DB Url:");

        url.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User");

        user.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password:");

        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        test_btn.setText("Test");
        test_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_btnActionPerformed(evt);
            }
        });

        checkDB.setText("Checked for set data all of  fields");
        checkDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dbConnectPanelLayout = new javax.swing.GroupLayout(dbConnectPanel);
        dbConnectPanel.setLayout(dbConnectPanelLayout);
        dbConnectPanelLayout.setHorizontalGroup(
            dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbConnectPanelLayout.createSequentialGroup()
                .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbConnectPanelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(dbConnectTitle))
                    .addGroup(dbConnectPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(dbConnectPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dbConnectPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dbConnectPanelLayout.createSequentialGroup()
                                .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(348, 348, 348))))
                    .addGroup(dbConnectPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dbConnectPanelLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(test_btn)
                                .addGap(18, 18, 18)
                                .addComponent(save_btn))
                            .addComponent(checkDB))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        dbConnectPanelLayout.setVerticalGroup(
            dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbConnectPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(dbConnectTitle)
                .addGap(50, 50, 50)
                .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driver))
                .addGap(18, 18, 18)
                .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(checkDB)
                .addGap(21, 21, 21)
                .addGroup(dbConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(test_btn)
                    .addComponent(save_btn))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        databaseTabPane.addTab("Exist Database", dbConnectPanel);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Create Database");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Driver:");

        driver_c.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        driver_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driver_cActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Domain Url:");

        url_c.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("User");

        user_c.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password:");

        password_c.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        create_btn.setText("Save");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });

        test_con_btn.setText("Test");
        test_con_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_con_btnActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DB Name:");

        dbName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        check_create.setText("Checked for set data all of  fields");
        check_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dbCreatePannelLayout = new javax.swing.GroupLayout(dbCreatePannel);
        dbCreatePannel.setLayout(dbCreatePannelLayout);
        dbCreatePannelLayout.setHorizontalGroup(
            dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dbCreatePannelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(test_con_btn)
                .addGap(18, 18, 18)
                .addComponent(create_btn)
                .addGap(151, 151, 151))
            .addGroup(dbCreatePannelLayout.createSequentialGroup()
                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbCreatePannelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel3))
                    .addGroup(dbCreatePannelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(dbCreatePannelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(url_c, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dbCreatePannelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(driver_c, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(user_c, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_c, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dbCreatePannelLayout.createSequentialGroup()
                                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(348, 348, 348))
                            .addGroup(dbCreatePannelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dbName, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dbCreatePannelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(check_create)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        dbCreatePannelLayout.setVerticalGroup(
            dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbCreatePannelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driver_c))
                .addGap(18, 18, 18)
                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(url_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(check_create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(dbCreatePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(test_con_btn)
                    .addComponent(create_btn))
                .addGap(24, 24, 24))
        );

        databaseTabPane.addTab("Create Database", dbCreatePannel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(databaseTabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(databaseTabPane)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void driverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed

        if (val.existedDbURLTest(url.getText())) {

            if (softSave == true) {
                try {
                    Hash hash = new Hash();
                    if (db.checkDriver(driver.getText(), url.getText(), user.getText(), password.getText())) {

                        File file = new File("src/data/MainServer.dat");
                        if (file.exists()) {
                            file.delete();
                        }
                        try {
                            file.createNewFile();
                        } catch (IOException ex) {
                            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try ( FileWriter myWriter = new FileWriter("src/data/MainServer.dat")) {
                            myWriter.write(hash.encrypt(driver.getText()) + "\n");
                            myWriter.write(hash.encrypt(url.getText()) + "\n");
                            myWriter.write(hash.encrypt(user.getText()) + "\n");
                            myWriter.write(hash.encrypt(password.getText()) + "\n");
                            ServerDBConnect.soft_driver = driver.getText();
                            ServerDBConnect.soft_url = url.getText();
                            ServerDBConnect.soft_user = user.getText();
                            ServerDBConnect.soft_pass = password.getText();
                            myWriter.close();
                            dispose();

                            try {
                                 //check licence
                                File licenceFile = new File("src/data/Licence.dat");
                                String licenceData = "";
                                if (!licenceFile.exists()) {
                                    dispose();
                                    new LicenceKeyActivation().setVisible(true);
                                } else {
                                    try ( Scanner data = new Scanner(licenceFile)) {
                                        int i = 0;
                                        if (data.hasNextLine()) {
                                            licenceData = data.nextLine();
                                        }
                                        data.close();
                                        ServerDBConnect sdbc = new ServerDBConnect();
                                        boolean check = sdbc.checkLicence(licenceData);
                                        System.out.println(licenceData);
                                        if (check) {
                                            dispose();
                                            if (LicenceClass.checkExpiredDate() == false) {
                                                if (LicenceClass.checkUserUse() == false) {
                                                    DataManage dm = new DataManage();
                                                    try {
                                                        String[] inf = sdbc.getUUID();
                                                        if (sdbc.insertOrUpdateClientUUID(licenceData, inf[0], inf[1])) {
                                                            // System.out.println(LicenceClass.db_support);
                                                            //database support yes
                                                            if (LicenceClass.db_support.equals("Yes")) {
                                                                sdbc.customerDbConnect(licenceData);
                                                            } else {
                                                                if (dm.fileExist("src/data/data.dat")) {
                                                                    dm.getDbConnected("src/data/data.dat");
                                                                } else {
                                                                    dispose();
                                                                    new DBConnect().setVisible(true);
                                                                }
                                                            }
                                                        }
                                                    } catch (IOException ex) {
                                                        Logger.getLogger(LicenceKeyActivation.class.getName()).log(Level.SEVERE, null, ex);
                                                    }
                                                } else {
                                                    JOptionPane.showConfirmDialog(null, "Your licence have crossed limit of max user.You can't able to use this licence.");
                                                }
                                            } else {
                                                JOptionPane.showConfirmDialog(null, "Licence date is Expired, Please Renew licence.");
                                            }
                                            dispose();
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Your Licence key is invalid ");
                                            new LicenceKeyActivation().setVisible(true);
                                            dispose();
                                        }
                                    }

                                }
                            } catch (IOException e) {
                                System.out.println("An error occurred.");
                                e.printStackTrace();
                            }

                        } catch (IOException e) {
                            System.out.println("An error occurred.");
                            e.printStackTrace();
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    Hash hash = new Hash();
                    if (db.checkDriver(driver.getText(), url.getText(), user.getText(), password.getText())) {

                        File file = new File("src/data/data.dat");
                        if (file.exists()) {
                            file.delete();
                        }
                        try {
                            file.createNewFile();
                        } catch (IOException ex) {
                            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try ( FileWriter myWriter = new FileWriter("src/data/data.dat")) {
                            myWriter.write(hash.encrypt(driver.getText()) + "\n");
                            myWriter.write(hash.encrypt(url.getText()) + "\n");
                            myWriter.write(hash.encrypt(user.getText()) + "\n");
                            myWriter.write(hash.encrypt(password.getText()) + "\n");
                            DatabaseConector.driver = driver.getText();
                            DatabaseConector.url = url.getText();
                            DatabaseConector.user = user.getText();
                            DatabaseConector.pass = password.getText();
                            myWriter.close();
                            dispose();
                            if (new DatabaseConector().checkAdmin()) {
                                new Login().setVisible(true);
                            } else {
                                new AddAdmin().setVisible(true);
                            }
                        } catch (IOException e) {
                            System.out.println("An error occurred.");
                            e.printStackTrace();
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void test_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_btnActionPerformed

        if (val.existedDbURLTest(url.getText())) {
            if (db.checkDriver(driver.getText(), url.getText(), user.getText(), password.getText())) {
                JOptionPane.showMessageDialog(null, "Connection is success");
            }
        }
    }//GEN-LAST:event_test_btnActionPerformed

    private void driver_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driver_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driver_cActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        boolean dbvalid = val.isNullOrEmpty(dbName.getText());
        if (dbvalid) {
            JOptionPane.showMessageDialog(null, "Database name must not be empty");
        } else {
            String furl;
            if ((url_c.getText().length() - 1) == url_c.getText().lastIndexOf("/")) {
                furl = url_c.getText();
            } else {
                furl = url_c.getText() + "/";
            }

            boolean check = db.createDatabase(driver_c.getText(), furl, user_c.getText(), password_c.getText(), dbName.getText());
            if (check == true) {
                try {
                    Hash hash = new Hash();
                    if (db.checkDriver(driver_c.getText(), furl + dbName.getText(), user_c.getText(), password_c.getText())) {

                        File file = new File("src/data/data.dat");
                        if (file.exists()) {
                            file.delete();
                        }
                        try {
                            file.createNewFile();
                        } catch (IOException ex) {
                            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try ( FileWriter myWriter = new FileWriter("src/data/data.dat")) {
                            myWriter.write(hash.encrypt(driver_c.getText()) + "\n");
                            myWriter.write(hash.encrypt(furl + dbName.getText()) + "\n");
                            myWriter.write(hash.encrypt(user_c.getText()) + "\n");
                            myWriter.write(hash.encrypt(password_c.getText()) + "\n");
                            DatabaseConector.driver = driver_c.getText();
                            DatabaseConector.url = furl + dbName.getText();
                            DatabaseConector.user = user_c.getText();
                            DatabaseConector.pass = password_c.getText();
                            myWriter.close();
                            dispose();
                            if (new DatabaseConector().checkAdmin()) {
                                new Login().setVisible(true);
                            } else {
                                new AddAdmin().setVisible(true);
                            }
                        } catch (IOException e) {
                            System.out.println("An error occurred.");
                            e.printStackTrace();
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_create_btnActionPerformed

    private void test_con_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_con_btnActionPerformed
        boolean dbvalid = val.isNullOrEmpty(dbName.getText());
        if (dbvalid) {
            JOptionPane.showMessageDialog(null, "Database name must not be empty");
        } else {
            String furl;
            if ((url_c.getText().length() - 1) == url_c.getText().lastIndexOf("/")) {
                furl = url_c.getText();
            } else {
                furl = url_c.getText() + "/";
            }
            if (db.checkDriver(driver_c.getText(), furl, user_c.getText(), password_c.getText())) {
                if (db.checkDatabase(dbName.getText())) {
                    JOptionPane.showMessageDialog(null, dbName.getText()+" Database is available for you.");
                }
                
            }

        }

    }//GEN-LAST:event_test_con_btnActionPerformed

    private void check_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_createActionPerformed
        if (check_create.isSelected()) {
            driver_c.setText("com.mysql.jdbc.Driver");
            url_c.setText("jdbc:mysql://localhost:3306/");
            user_c.setText("root");
            dbName.setText("test");
        } else {
            driver_c.setText("");
            url_c.setText("");
            user_c.setText("");
            dbName.setText("");
        }
    }//GEN-LAST:event_check_createActionPerformed

    private void checkDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDBActionPerformed
        if (checkDB.isSelected()) {
            driver.setText("com.mysql.jdbc.Driver");
            url.setText("jdbc:mysql://localhost:3306/");
            user.setText("root");
        } else {
            driver.setText("");
            url.setText("");
            user.setText("");
        }
    }//GEN-LAST:event_checkDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBConnect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkDB;
    private javax.swing.JCheckBox check_create;
    private javax.swing.JButton create_btn;
    private javax.swing.JTabbedPane databaseTabPane;
    private javax.swing.JPanel dbConnectPanel;
    private javax.swing.JLabel dbConnectTitle;
    private javax.swing.JPanel dbCreatePannel;
    private javax.swing.JTextField dbName;
    private javax.swing.JTextField driver;
    private javax.swing.JTextField driver_c;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField password;
    private javax.swing.JTextField password_c;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton test_btn;
    private javax.swing.JButton test_con_btn;
    private javax.swing.JTextField url;
    private javax.swing.JTextField url_c;
    private javax.swing.JTextField user;
    private javax.swing.JTextField user_c;
    // End of variables declaration//GEN-END:variables
}
